### ISSUE TITLE
Sometimes ruleset disappears from Custom Rules menu

### ISSUE THREAD

**Issue by jborgers** [amitdev/PMD-Intellij#105]
The custom rules sets are sometimes just not available anymore from the Custom Rules menu. 
While it is still in the list of rulesets in the Preferences/Setting of the PMD plugin. 
What helps is to remove it there and add it again, then it will also be available from the menu again. It is a work around, it should be fixed.

**Comment by ferng** [comment]
I'm seeing this too fairly regularly, I'm on 1.8.18 running on Build #IU-221.5080.210 Build #IU-221.5080.210, apple M1.

it's really annoying

**Comment by jborgers** [comment]
It might be solved with the newest release

**Comment by ferng** [comment]
hi @jborgers i'e just updated, i'll keep an eye on it over the next few days

**Comment by ferng** [comment]
hi @jborgers, first thing this morning went to run pmd and the ruleset has disappeared, i guess you've been lucky so for

**Comment by jborgers** [comment]
Reproducible with > 1 project open. Configuration is per project, while the user expects settings on IntelliJ/plugin level.
When a second project is opened which does not have the rulesets in PMD settings, it will clear the shared menu.

Workable solution is when > 1 projects open, merge the rule sets of shared actions (menu) and current project into the menu. So 1. you keep rulesets in menu, and 2. in effect you cannot remove the rulesets. With 1 project open it behaves as before, so you can remove rulesets. Then the menu reflects 1:1 the configuration.

Better solution would be an ActionManager for each project and one shared configuration/settings for all projects, as expected by user.

**Comment by jborgers** [comment]
Edit and OK a ruleset in the configuration (so without change) will now update the menu from the configuration.
