### ISSUE TITLE
Support of Java 15+

### ISSUE THREAD

**Issue by efinder2** [amitdev/PMD-Intellij#124]
the plugin shows a processing error for Java Text blocks. 
![image](https://user-images.githubusercontent.com/12611194/217573027-5c55e3d0-83a5-4f88-a473-56642c132ea4.png)
Tested it with same pmd version and rule set via command line. It works fine. I there a property in Intellij wich affects the Java version of the plugin?

**Comment by jborgers** [comment]
Hi @efinder2,

You can set the version of Java supported by the PMD Plugin:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/24591067/217575336-9fd0d93a-deec-4827-b6d8-8bedd94f021d.png">

**Comment by efinder2** [comment]
thanks. hadn't seen the options.
