### ISSUE TITLE
Plugin doesn't show up in the menu

### ISSUE THREAD

**Issue by Zappes** [amitdev/PMD-Intellij#15]
I installed PMDPlugin 1.7.1 in Idea Ultimate 13.1.6, but it doesn't show up anywhere. I would have expected some kind of menu entry in tools or analyze, but there's neither.

**Comment by amitdev** [comment]
You should see it if you right-click on a file or directory in Idea. Then you can run PMD on the selected file(s). There should also be a setting page entry inside Idea settings to configure custom rules etc.

**Comment by Zappes** [comment]
Thanks a lot, that helped! I guess that solves the issue.
