### ISSUE TITLE
NullPointerException in setting number of threads to use

### ISSUE THREAD

**Issue by jborgers** [amitdev/PMD-Intellij#151]
When setting the value for the first time, to 4, and pressing OK, I get:
![image](https://github.com/amitdev/PMD-Intellij/assets/24591067/c3f07fcb-ad40-42dc-a2fc-e0747f2a3f4c)

**Comment by martenbohlin** [comment]
I am taking a look at this

**Comment by martenbohlin** [comment]
The problem is that there has not been any new release done after this fix was merged.

**Comment by jborgers** [comment]
Okay, thanks @martenbohlin for the update. Is #156 solved in the PR as well?

**Comment by martenbohlin** [comment]
No, but I have made PR #157 to fix that

**Comment by jborgers** [comment]
works in 1.9.2
