### ISSUE TITLE
Improvement: Add filter by priority

### ISSUE THREAD

**Issue by martin5211** [amitdev/PMD-Intellij#160]
We have a custom ruleset; most of the rules are priority 4, which will keep the build intact. It would be nice to have a filtering capability in the PMD tab to show any issue with a priority of less than four and focus on it by severity.

The generated pmd.xml file with the results of the PMD execution has these priority attributes. I'm unsure if the executions done by the custom ruleset with the plug-in have the ability, either.

**Comment by jborgers** [comment]
Hi Martin, the violations are ordered by severity in the results panel. This way, you can focus on the violations by severity, so highest severity first. 
What is exactly the feature you are missing?

**Comment by jborgers** [comment]
Will close this issue if still no answer in two weeks from now.
