### ISSUE TITLE
Add support for PMD 7 (and Java 21)

### ISSUE THREAD

**Issue by uhafner** [amitdev/PMD-Intellij#161]
PMD 7 is now available and provides support for Java 21. It would be helpful if the PMD IntelliJ plugin would also support this new version.

**Comment by jborgers** [comment]
Agreed. A difficulty here is that PMD 7 is not backwards compatible, that is, custom rules written for PMD 6 will not work in PMD 7. Those rules will have to be re-written.

**Comment by jborgers** [comment]
Note that you can specify '20-preview' as Target JDK. All Java 21 syntax I tested was recognized this way.

**Comment by cree01** [comment]
I would really appreciate to move to PMD 7. There is no PMD 7 plugin for intellij right now....

**Comment by martenbohlin** [comment]
Is anyone looking into this, or should I make an attempt and see if I can get it working?

**Comment by jborgers** [comment]
Yes, please look into it and share your experiences here. Difficulty will
be to still support PMD 6 custom rules since PMD 7 is not backwards
compatible. This is now easier to test with the new plugin release by
choosing the custom jpinpoint-rules from the drop down list.

Note that it is more clear now what java versions are supported. PMD 6 goes
up to java 20-preview. Effectively it supports java 21, at least for what I
have tested. If you find otherwise, please let me know here.
So maybe that takes some pressure away from supporting PMD 7.






Op za 20 apr 2024 08:53 schreef Mårten Bohlin ***@***.***>:

**Comment by martenbohlin** [comment]
I think the best solution would be to release a new major version of the plugin that uses PMD 7. And if you want  to continue to use PMD 6 you will need to pin the plugin to the current version of the plugin.

**Comment by jborgers** [comment]
See [Migration to PMD 7 guide](https://pmd.github.io/pmd/pmd_userdocs_migrating_to_pmd7.html)

**Comment by jborgers** [comment]
We have about 120 rules which need to be migrated, which takes quite some time. 
I would not like for our users to automatically upgrade to the new plugin version and ending up without the possibility to use the rules, and being puzzled about why. So I'd like it to be very clear that if the user chooses to upgrade, that the consequent is that the PMD 6 custom rules don't work anymore.

**Comment by martenbohlin** [comment]
I have made a PR for a upgrade to PMD 7 and it seems to works fine but needs more testing. 

We have started to use the new improved rules that PMD7 offers, and for us it is an obstacle to not see all the rules in IntelliJ.  
One solution would be to publish a PMD7 compatible plugin under a different name, but then I guess many users would miss that there is an upgraded version.

**Comment by jborgers** [comment]
Hi Marten,

I can help with some testing on Friday afternoon Amsterdam time zone.


Op zo 21 apr 2024 om 14:28 schreef Mårten Bohlin ***@***.***>:

**Comment by jborgers** [comment]
I was busy releasing sonar-pmd plugin and testing it. 
Somehow we need to validate if a custom rules set when loaded is of the correct version, if not, show a proper message what to do (revert to pmd6 version.)

**Comment by jborgers** [comment]
I didn't find a property on ruleset level which specifies the pmd version (6 or 7).
A difference I see is in rule properties:
`<property name="version" value="2.0"/>`
is used for PMD 6. 
PMD 7 uses version 3.1 as default and the property is not to be specified.

**Comment by jborgers** [comment]
See #172 and #173

**Comment by jborgers** [comment]
Tested OK in version 2.0.0
