### ISSUE TITLE
Tools -> PMD -> PreDefined menu is disabled

### ISSUE THREAD

**Issue by michaelJustin** [amitdev/PMD-Intellij#174]
Plugin version: 2.0.0
IDE version: IntelliJ IDEA 2024.1.1 (Ultimate Edition), Build #IU-241.15989.150, built on April 29, 2024

What I tried so far:
* Uninstalling and installing the plugin did not help.

What I did as a workaround:
* Extracted pmd-java-7.1.0.jar and configured the quickstart.xml as a custom rule set.

**Comment by amitdev** [comment]
@michaelJustin Thanks for reporting this. This should be fixed in the updated plugin (2.0.1).
