### ISSUE TITLE
Hide old versions in marketplace?

### ISSUE THREAD

**Issue by adangel** [amitdev/PMD-Intellij#200]
The problem:

When JetBrains releases a new version and updates your local installation of IntelliJ, they try to install the same plugins as before.

For the PMDPlugin, they find the version 1.8.18 as the latest version, that is allegedly compatible:
https://plugins.jetbrains.com/plugin/1137-pmd/versions/stable/129323

1.8.18 claims to be compatible with 2020.1 and any later version (e.g. 2025.1...)

However, this is not true.... this results in various errors ("The 1.8.x version creates a lot of NPEs right after the start...").

This problem will arise for every new version the JetBrains releases.

Possible solution:

One way to deal with that is, to hide the old versions. If @amitdev or @jborgers have access to the marketplace, this is possible:
https://plugins.jetbrains.com/docs/marketplace/plugin-updates.html#hide-a-plugin-update
(or the old versions could be removed completely)

I assume (not tested...) that then the users would see in the plugin list of IntelliJ after an upgrade, that PMD Plugin is not compatible anymore and there is no compatible version available.

Alternative:

Alternatively, we could start claming forward compatibility again, by just configuring the minimum version of IntelliJ the plugin is compatible with. That means, that the latest version would be installable always in the latest IntelliJ version - but it might not work correctly. At least, there is a chance, that is "just" works.

**Comment by jborgers** [comment]
In my opinion we should hide or remove the 1.8.18 version.

Claiming forward compatibility on the newest version will likely fail on the new intelliJ version, so I am not in favor of that. We should however act more quickly when a new version arrives, in my view .

@amitdev can you hide/remove version 1.8.18? I don't seem to have access rights to the marketplace.

**Comment by adangel** [comment]
> hide/remove version 1.8.18

note, this means all versions below 1.8.18 as well - 1.8.19 is the first version, that defines an upper bound, but not the older versions (1.1 - 1.8.18).

**Comment by jborgers** [comment]
We can be notified about new IntelliJ releases, I subscribed here: https://www.jetbrains.com/idea/nextversion/

**Comment by amitdev** [comment]
I've requested deletion of old versions

**Comment by adangel** [comment]
Seems like this didn't work - the old versions are still available:
https://plugins.jetbrains.com/plugin/1137-pmd/versions

![Image](https://github.com/user-attachments/assets/c16a924f-131f-4152-a140-f63014cf5571)

See also https://github.com/amitdev/PMD-Intellij/issues/176#issuecomment-2655867934
