### ISSUE TITLE
Missing "Other Settings" menu option with IntelliJ 2016.1

### ISSUE THREAD

**Issue by cakier** [amitdev/PMD-Intellij#26]
When using the latest PMDPlugin v1.7.7 with IntelliJ 2016.1, the "PMD" option under IntelliJ's Settings >> Other Settings menu is no longer present. As a result, there is no way to specify custom rulesets for PMDPlugin when using the latest version of IntelliJ.

This issue is not present when using IntelliJ 15.0.x.

**Comment by amitdev** [comment]
Thanks for reporting this, I'll post an update soon.

**Comment by cakier** [comment]
Thanks for the quick fix! The plugin works beautifully in 2016.1 now.
