### ISSUE TITLE
Scanning XML files

### ISSUE THREAD

**Issue by sushi2k** [amitdev/PMD-Intellij#28]
Hi Amit,

according to the project page of PMD also XML files can be scanned (https://pmd.github.io/). Is it therefore possible to check for the existence of attributes or tags in XML files with PMD-IntelliJ? If so, how can it be done?

I tried with the following rule to check if allowBackup is set as attribute in an AndroidManifest.xml, but it cannot be detected. 

```
  <rule class="net.sourceforge.pmd.lang.rule.XPathRule" deprecated="false" dfa="false" language="java" message="" name="" typeResultion="true">
    <description>AllowBackup - android:allowBackup is set</description>
    <priority>3</priority>
    <properties>
      <property name="xpath">
        <value>//Name[matches(@Image,'allowBackup','i')]</value>
      </property>
      <property name="version" value="2.0"/>
    </properties>
    <example/>
  </rule>
```

Also the following value in the rule above was not working and the attribute could not be identified. 

`<value>//Name[contains(lower-case(@Image),'allowBackup')]</value>
`

**Comment by amitdev** [comment]
Currently only java file type is supported. Let me see if I get some time to add support for other files later.

**Comment by sushi2k** [comment]
Sure. Thanks for your response.

**Comment by jborgers** [comment]
Hi Amit, 

I have the same request. I wrote a custom pmd rule for maven pom.xml files and it works perfectly in the pmd tool itself. However, the PMDPlugin just fails when I add this rule in the ruleset. I would like PMDPlugin to just work with the xml rule like pmd itself.
Additionally, I have trouble finding the log file where PMDPlugin reports these kinds of errors when it fails.

Regards, Jeroen

**Comment by jborgers** [comment]
Maybe I can help with implementing the feature? If you can point me to the source file(s) to change would be handy. PMDInvoker?

**Comment by jborgers** [comment]
I created a fix for this issue.

**Comment by amitdev** [comment]
@jborgers 👍 Can you raise a PR?

**Comment by jborgers** [comment]
Hi Amit,

What exactly do you mean?

Regards, Jeroen


Op 6 feb. 2018 01:14 schreef "Amit Dev" <notifications@github.com>:

@jborgers <https://github.com/jborgers> 👍 Can you raise a PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amitdev/PMD-Intellij/issues/28#issuecomment-363265459>,
or mute the thread

**Comment by jborgers** [comment]
Ah, pull request, right. Will work on it.

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, www jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com

2018-02-06 7:55 GMT+01:00 Jeroen Borgers <jborgers@jpinpoint.com>:
