### ISSUE TITLE
Plugin incompatible with Android Studio 2.1

### ISSUE THREAD

**Issue by davidschreiber** [amitdev/PMD-Intellij#29]
The plugin is not available for using with Android Studio 2.1. Also including the plugin locally does not work, since the specified `idea-version` is too new. I've tried enabling the plugin by downgrading to version `143` (which I think is the basis for Android Studio 2.1). But while installation is not prevented using this setting, the plugin seems to be automatically removed at startup, silently without generating any error.

Related issue #18

**Comment by amitdev** [comment]
How did you downgrade the version? The problem is new version of Idea has removed some old APIs. Can you try installing the previous version of the plugin?

**Comment by amitdev** [comment]
Assume this is no longer an issue

**Comment by razon30** [comment]
http://stackoverflow.com/questions/36589908/incompatible-bitbucket-plugin-1-2-1-for-android-studio-2-0-2-1/36607806#36607806
