### ISSUE TITLE
Run PMD check before commit

### ISSUE THREAD

**Issue by Geniy00** [amitdev/PMD-Intellij#30]
It will be nice to implement next enhancement:
run PMD check on changelist before commit.
It has already been implemented for similar tools: checkstyle, findbugs
![image](https://cloud.githubusercontent.com/assets/1192251/15815181/f6ec362c-2bd3-11e6-82f2-a158d96e1a9a.png)

**Comment by j-musca** [comment]
I would really like to see this implemented!

**Comment by stefanthurnherr** [comment]
Would be a great feature to have!

**Comment by amitdev** [comment]
Let me see if I get some free time to do this. Mean while pull requests are welcome :)

**Comment by lucianovdveekens** [comment]
I believe this issue can be closed.

**Comment by SJrX** [comment]
I believe it can be closed as well.

**Comment by jborgers** [comment]
I agree. I guess both @Geniy00 and @amitdev are able to close it.
