### ISSUE TITLE
IntelliJ IDEA 2016.2 How to add a custom RuleSet ?

### ISSUE THREAD

**Issue by gcstang** [amitdev/PMD-Intellij#31]
When I add a ruleset I get a Couldn't find the class ...  error.

Do you have an example on how I would add a new custom ruleset that works?
Maybe tell me what classpath it's looking at or what I need to change in the ruleset file to get it to work?

Thank you or your help.

**Comment by amitdev** [comment]
It should work. Do you have a sample ruleset that is failing?

**Comment by gcstang** [comment]
Here is an example but where does the java expected to be located?

**Comment by amitdev** [comment]
Go to PMD setting  and add the custom rule. See issue #32 to see a sample rule.

**Comment by gcstang** [comment]
The example doesn't look like a custom example to me, it looks like it's calling something that already exists.  I've attached my ruleset.xml and java source file as an example, maybe you can describe how I would add this to PMD inside of IntelliJ.

Archive should have two files:
1. ruleset.xml
2. HardcodedPassword.java

[Archive.zip](https://github.com/amitdev/PMD-Intellij/files/548904/Archive.zip)

**Comment by amitdev** [comment]
You need to add the class file to idea's classpath. One option is inside the plugin path (see https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs). For example on Linux, it could be ` ~/.IdeaIC2016.2/system/plugins-sandbox/plugins/PMD-Intellij/classes/`

**Comment by gcstang** [comment]
Thank you, I have it working now.

For Others reference if needed.
On Mac
~/Library/Application Support/<PRODUCT><VERSION>/PMD-Intellij
mkdir classes
copy classes structure into the classes directory and restart IDEA
