### ISSUE TITLE
Update to PMD 5.5.1 to support Apex?

### ISSUE THREAD

**Issue by arbokrad** [amitdev/PMD-Intellij#33]
The Salesforce Apex language has been added to PMD in versions 5.5.x since the last time this plugin was updated, can the plugin be updated to support the new features?

**Comment by amitdev** [comment]
I've updated to 5.5.1. Support for Apex might need some more change. I'll check later.

**Comment by mdemin914** [comment]
This would be awesome to have! Any chance you checked?

**Comment by gussamer** [comment]
I'd love to use this for my apex development, any idea on when apex will be supported?

**Comment by thvd** [comment]
IlluminatedCloud does support PMD in Apex code

**Comment by dave-sfdc** [comment]
I am trying to use PMD in IntelliJ IDE using illuminated cloud. When I run PMD using pre-defined rules, no violations are reported. When I try to import custom rules from PMD's website, it does not load the custom rules and throws as error as shared in attachment. 
![image](https://user-images.githubusercontent.com/17682618/43739385-d2b5f5a4-9995-11e8-8e82-e5d9860d3295.png)

Just to be clear, I am trying to run PMD for salesforce( apex) rules and want to see the bugs/errors from PMD in the IDE itself.  I have searched all over the internet, did not find any support for it. Does PMD on intelliJ support apex ?

**Comment by amitdev** [comment]
I've added support to use custom rulesets to scan apex files (.cls and .trigger).
