### ISSUE TITLE
PMD IDEA Plugin 1.8.1.bugs

### ISSUE THREAD

**Issue by VKaiserSH** [amitdev/PMD-Intellij#36]
Hi, I have some problems with the running of PMD plugin version 1.8.1.
1. If I run PMD in IDEA IDE, I get always the error message "Error while parsing .../MyEnum.java".
This class MyEnum (the name is changed here) is an enum-class  with only one String-member and with two methods get/set.
But the maven PMD-plugin works fine .

2. This IDEA-PMD plugin 1.8.1 doesn’t support the jsp/jsf rules
"rulesets/jsp/basic-jsf.xml" and "rulesets/jsp/basic.xml". Why?

3. The properties of the rules are not supported. Example:
I use custom PMD ruleset and added it into the PMD plugin in IDEA IDE.
I have configured the rule "CommentSize" in the corresponding XML file as follows:
rule ref="rulesets/java/comments.xml" name="CommentSize"  
    properties 
	     property name="maxLineLength" value="160" 
	     property name="maxLines" value="30"   
    properties 
rule 
But I still get the messages "Comment is too large: Line too long" and "Comment is too large: Too many lines", because the plugin uses the default values 80 and 6 for these properties and because I have long comments in my code. Eclipse PMD plugin doesn't load these properties maxLineLength and maxLines from the ruleset file too, but it has at lest the possibility to edit the rules in the IDE. Your plugin doesn't do that unfortunately.

Can we help me?
Best regards, 
Valerius Kaiser, Germany

**Comment by maming123450** [comment]
I hava same problem 。This leds I can't use pmd to analyze code。When be repaired ？

**Comment by jborgers** [comment]
For item 1: did you configure the version of Java in PMDPlugin to your used version? 
Because of (I assume) a bug, if you change the version in the plugin conf, you need to tab out of the input field in order to make the change permanent.

**Comment by jborgers** [comment]
In recent versions of the plugin, the processing errors are more clear and informative. You can also jump to the problematic line in the analyzed source code. Does that help?
