### ISSUE TITLE
PMD plugin is not listing the custom rules

### ISSUE THREAD

**Issue by Suszi** [amitdev/PMD-Intellij#39]
I added a custom rule in my project to PMD, but it is not listed.
![pmd_plugin](https://user-images.githubusercontent.com/9104652/27899859-40df54a0-622c-11e7-876e-c0b1e6e74f9d.png)
When I try to run it, there are four rules listed.
![pmd_rules](https://user-images.githubusercontent.com/9104652/27899974-af46d85a-622c-11e7-980e-d46bb6b3d513.png)
PMD plugin version:
1.8.2
IntelliJ version:
2017.1.5

**Comment by amitdev** [comment]
I've seen it happen sometimes - restarting idea should show it - please try. Not sure when I can fix this.

**Comment by Suszi** [comment]
I already restarted.
And I tried to remove and add the rule again.
Both not helped.

**Comment by jborgers** [comment]
I fixed this problem (and others). I will create a pull request.
