### ISSUE TITLE
Upgrade pmd version to 6.3.0

### ISSUE THREAD

**Issue by BenSartor** [amitdev/PMD-Intellij#48]
Hi,

thank for the nice plugin!
Would you mind upgrading pmd to the latest version 6.3.0?

Kind regards,
 Ben

**Comment by amitdev** [comment]
Requires idea 2018.*

**Comment by BenSartor** [comment]
Hi @amitdev,

thanks a lot for your quick reply and the update!

I would have expected that you have to change the following line in the file PMD-Intellij.iml to update pmd:
{code}
<orderEntry type="library" name="pmd-core-6.0.1" level="project" />
{code}
But I guess, this just shows that I have no idea about IntelliJ Plugin Development :)

King regards,
 Ben
