### ISSUE TITLE
Add custom ruleset

### ISSUE THREAD

**Issue by Kevmo92** [amitdev/PMD-Intellij#49]
I've seen multiple issues that express confusion on how to add a custom ruleset to intellij.
I'm opening this issue to hopefully understand what class file I need to put into the classes directory.

I'm simply trying to add a custom ruleset like:

```xml
<?xml version="1.0"?>

<ruleset name="full-visual-force-pmd-ruleset"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
    <description>VisualForce - All Rules</description>

    <!-- Security -->
    <rule ref="category/vf/security.xml/VfCsrf" />
    <rule ref="category/vf/security.xml/VfUnescapeEl" />

</ruleset>
```

When I try to add the ruleset I get:
`The selected file is not a vaild PMD ruleset: Can't find the resource 'category/vf/security.xml' for rule VfCsrf. Make sure the resource is a valid file or URL and is on the CLASSPATH`

I've dug into this [issue](https://github.com/amitdev/PMD-Intellij/issues/31)
And I've created a `classes` directory under `~/Library/Application\ Support/ideaIC2018.1/PMD-Intellij`, but i have no clue what the class file is or what it should look like...

I'm using pmd 6.2.0 and I'm able to run the custom ruleset outside of IntelliJ.

Any help is appreciated.

**Comment by amitdev** [comment]
It is probably because the visualforce rules are not currently supported. Custom rules for java should work.

**Comment by Kevmo92** [comment]
@amitdev Oh, that would make sense. I'm trying to run custom apex rulesets. Is java the only supported language with this plugin?

**Comment by amitdev** [comment]
apex is supported now.
