### ISSUE TITLE
SuppressWarnings annotation errors

### ISSUE THREAD

**Issue by simeonKondr** [amitdev/PMD-Intellij#61]
apex 
PMD Version: 6.6.0

Description: when I'm trying to use @SuppressWarnings('PMD'), Idea shows me warnings, and also when I'm trying to use quick format for this file it does not work

Code Sample demonstrating the issue:
![screenshot from 2018-09-05 13-46-29](https://user-images.githubusercontent.com/42644177/45095168-112f8280-b126-11e8-82fa-6daa7bed5ffc.png)
![123](https://user-images.githubusercontent.com/42644177/45095169-112f8280-b126-11e8-825d-73f30ad20696.png)
![screenshot from 2018-09-05 13-49-40](https://user-images.githubusercontent.com/42644177/45095170-11c81900-b126-11e8-832a-8e2537426725.png)

**Comment by simeonKondr** [comment]
https://github.com/pmd/pmd/issues/1333#event-1827778660

**Comment by xylo** [comment]
@simeonKondr Check your quotes. You use ' instead of " for strings.
