### ISSUE TITLE
adding custom ruleset required IntelliJ restart

### ISSUE THREAD

**Issue by davcamer** [amitdev/PMD-Intellij#8]
I am using IntelliJ Ultimate 13.1.4 (Build #IU135.1230) on Mac OS X 10.9.4 on JRE 1.6.0_65-b14-462-11M4609 x86_64

Reproduction steps:
1. Open Preferences => PMD => +
2. Click Browse in the dialog box 
3. Navigate to the pmd.xml file in the resulting file chooser
4. The path to the file is displayed in the text box of the dialog
5. Click OK on the dialog

Expected:
- the path to the file should be listed in the list of custom rules
- the Custom Rules menu option should be active, and the file available to choose

Actual:
- nothing is listed in the list of custom rules (although the '-' and edit buttons become active)
- the Tools => Run PMD => Custom Rules menu is still disabled

After restarting IntelliJ, reality matched expectation. But, I wasn't expecting to have to restart, and there was no indication that I should.

**Comment by alexandertei** [comment]
This is still an issue as of today. 

I am running IntelliJ IDEA 14.1.3
Build #IU-141.1010, built on May 12, 2015
JRE: 1.8.0_45-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

The plugin version is 1.7.3. 

Reproduction and actual results are identical to the original report.

**Comment by nilsschmidthamburg** [comment]
This is still an issue as of today.

IntelliJ IDEA 15.0
Build: Idea-IU-143.381.42
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

The plugin version is 1.7.3.

Reproduction and actual results are identical to the original report.
