### ISSUE TITLE
Can not load Idea if ruleset is not find

### ISSUE THREAD

**Issue by humphrey71** [amitdev/PMD-Intellij#80]
Our company is using PMD to check the java code. I was trying this plugin on Idea yesterday by add our custom rule _pmd-ruleset.xml_, and thanks you guys it`s really helpful. But when I checkout another branch of our code without this _pmd-ruleset.xml_ and restart Idea, it pops up an error message and prevents Idea loading. I know it is caused by the file missing, but could you please help fix it not to prevent Idea loading?
![image](https://user-images.githubusercontent.com/9566876/101565839-db665c00-3a08-11eb-9ccf-6d4978c88d75.png)

**Comment by transdoc** [comment]
I would like to learn intellij plugin development and doing research on this issue and find a solution.

**Comment by jborgers** [comment]
Solved in release 1.8.18. Can be closed.
