### ISSUE TITLE
Ruleset not loading (also deadlock)

### ISSUE THREAD

**Issue by thiakil** [amitdev/PMD-Intellij#90]
Every time I load a project I get this error box, though this time it occurred while IDEA had its own modal open, and I can't actually close either of them. This was a project reload action triggered by another plugin, the error is normally dismissable on project open.
![image](https://user-images.githubusercontent.com/1788847/116329140-2f79ad80-a7fd-11eb-91a7-8062712e4c59.png)

I added the highlighted ruleset, though the other two appear to have been added automatically somehow..? They are standard files included with PMD.
![image](https://user-images.githubusercontent.com/1788847/116329253-87181900-a7fd-11eb-97db-02eed3a74c42.png)

**Comment by jborgers** [comment]
Solved in release 1.8.18. Can be closed.
